version: '3.7'

services:
  service-jenkins:
    container_name: jenkins_server_container
    image: jenkins/jenkins:lts
    user: root
    environment:
      SONARQUBE_HOST: sonarqube_server_container
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_data_volume:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_sonarqube_network
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
  service-sonar:
    container_name: sonarqube_server_container
    image: sonarqube:lts-community
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
      SONAR_SCANNER_OPTS: "--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED"
    ports:
      - "9001:9000"
    networks:
      - jenkins_sonarqube_network
    volumes:
      - ./sonarqube_home/conf/:/opt/sonarqube/conf
      - ./sonarqube_home/data/:/opt/sonarqube/data
      - ./sonarqube_home/logs/:/opt/sonarqube/logs
      - ./sonarqube_home/extensions/:/opt/sonarqube/extensions
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 3G

volumes:
  jenkins_data_volume:
    external: false

networks:
  jenkins_sonarqube_network:
    driver: bridge
    name: jenkins_sonarqube_network
